apiVersion: v1
kind: Service
metadata:
  name: redis-target
spec:
  type: NodePort
  selector:
    app: redis-target
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30001 # Host port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-target
  labels:
    app: redis-target
    meu-projeto/tipo: "alvo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-target
  template:
    metadata:
      labels:
        app: redis-target
      annotations:
        meu-projeto/prioridade: "alta"
    spec:
      containers:
      - name: redis
        image: redis:alpine
        command: ["redis-server", "--protected-mode", "no"]
        resources:
          requests:
            cpu: "100m" 
            memory: "128Mi"
        ports:
        - containerPort: 6379
